apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: shop
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /api/ {
            proxy_pass http://api.shop.svc.cluster.local/;
        }
    }