apiVersion: v1
kind: Namespace
metadata:
  name: shop
  labels:
    app.kubernetes.io/name: shop
    app.kubernetes.io/part-of: apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"